### PR TITLE
Act 2 enemies

### PR DESCRIPTION
**Pull request by ynks**

### CODE REVIEW

**Review by dariormt — APPROVED** [review]
GG, 
Next time do pull requests of no more than 150 lines, i´m to lazy for this

**Comment by ynks** [comment]
This are unity scenes its fucking unity's job to not make a 1 object change modify 120k lines of code lol

**Comment by ynks** [comment]
Have you changed anything on Club__Main and Containers__Main btw? @dariormt

**Comment by dariormt** [comment]
Ekis de

**Pull request merged**
